In [24]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

mood_data=pd.read_csv('food_choices.csv')

mood_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   GPA                           123 non-null    object 
 1   Gender                        125 non-null    int64  
 2   breakfast                     125 non-null    int64  
 3   calories_chicken              125 non-null    int64  
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64  
 7   comfort_food                  124 non-null    object 
 8   comfort_food_reasons          123 non-null    object 
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64  
 12  cuisine                       108 non-null    float64
 13  diet_

In [25]:
mood_data[['comfort_food_reasons', 'comfort_food']]

comfort_food_reasons  \
0                            we dont have comfort    
1                             Stress, bored, anger   
2                                  stress, sadness   
3                                          Boredom   
4                       Stress, boredom, cravings    
..                                             ...   
120                           boredom and sadness    
121                Loneliness / Homesick / Sadness   
122                                        sadness   
123  happiness, they are some of my favorite foods   
124               hormones, Premenstrual syndrome.   

                                comfort_food  
0                                       none  
1                chocolate, chips, ice cream  
2            frozen yogurt, pizza, fast food  
3           Pizza, Mac and cheese, ice cream  
4               Ice cream, chocolate, chips   
..                                       ...  
120  wine. mac and cheese, pizza, ice cream   
121               Pizza / Wings / Cheesecake  
122               rice, potato, seaweed soup  
123             Mac n Cheese, Lasagna, Pizza  
124             Chocolates, pizza, and Ritz.  

[125 rows x 2 columns]

In [34]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Identify categorical columns (replace with your actual column names)
categorical_cols = ['comfort_food_reasons', 'comfort_food']

# Create a LabelEncoder instance
le = LabelEncoder()

# Encode categorical columns
for col in categorical_cols:
    mood_data[col] = le.fit_transform(mood_data[col])

mood_data[['comfort_food_reasons', 'comfort_food']]


comfort_food_reasons  comfort_food
0                      98            91
1                      79            29
2                      89            58
3                       8           107
4                      85            66
..                    ...           ...
120                    11           124
121                    53           112
122                    60           117
123                    41            85
124                    42            44

[125 rows x 2 columns]

In [42]:
mood_data['comfort_food_reasons'].unique()

array([ 98,  79,  89,   8,  85,  58,  80,  47,   9,  78,  70,  63,  87,
        36,  74,  48,  69,  28,  40,  55,  65,  75,   1,  22,  93,  14,
        82,  72,  43,  26,  33,  34,  73,  30,  57,  97,  96,  23,   2,
        84,  44,  62,  19,  92,  95,  52,  25,  77,   7,  49,  50,  86,
        17,  64,  46,  60,   6,  90,  31,   5,  16,  15,   0,  71,  12,
        18,  38,  29,  68,  56,  24,  99,  83,  91,  51,  20,  39,  13,
        35,  94,  59,  32,   3,   4,  27,  21,  76,  45,  88,  61,  66,
        10,  67,  81,  54, 100,  37,  11,  53,  41,  42], dtype=int64)

In [47]:
#from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#labelencoder = LabelEncoder()
#for col in mood_data:
 #   mood_data[col] = labelencoder.fit_transform(mood_data[col])
X = mood_data[['comfort_food_reasons']].values[:100]
y = mood_data[['comfort_food']].values[:100]

print(y)

[[ 91]
 [ 29]
 [ 58]
 [107]
 [ 66]
 [  6]
 [ 34]
 [ 64]
 [ 52]
 [ 77]
 [ 94]
 [ 39]
 [ 50]
 [ 60]
 [102]
 [ 46]
 [118]
 [ 19]
 [ 32]
 [113]
 [ 54]
 [ 43]
 [  3]
 [ 14]
 [120]
 [ 35]
 [ 23]
 [ 13]
 [ 47]
 [122]
 [ 48]
 [ 17]
 [ 59]
 [ 70]
 [ 55]
 [ 86]
 [101]
 [ 28]
 [ 41]
 [  8]
 [106]
 [ 68]
 [ 69]
 [ 63]
 [116]
 [ 78]
 [115]
 [ 12]
 [104]
 [ 56]
 [114]
 [  2]
 [ 98]
 [ 57]
 [ 96]
 [ 20]
 [103]
 [ 99]
 [ 36]
 [ 84]
 [ 95]
 [ 89]
 [ 71]
 [ 10]
 [ 49]
 [ 76]
 [ 42]
 [ 61]
 [ 24]
 [ 97]
 [  1]
 [ 33]
 [110]
 [ 21]
 [  0]
 [ 81]
 [ 40]
 [100]
 [ 31]
 [ 26]
 [ 45]
 [  5]
 [105]
 [ 90]
 [ 93]
 [ 74]
 [ 16]
 [109]
 [ 75]
 [ 11]
 [ 22]
 [ 87]
 [ 30]
 [ 79]
 [  7]
 [ 53]
 [ 62]
 [ 80]
 [121]
 [ 82]]


In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2,random_state=0)

In [37]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [43]:
y_pred=regressor.predict(X_test)
y_pred

array([[61.89410452],
       [61.88462856],
       [61.57665996],
       [61.96517419],
       [61.66194357],
       [61.88936654],
       [61.64772964],
       [61.85620069],
       [61.6335157 ],
       [61.90358047],
       [61.88936654],
       [61.567184  ],
       [61.61930176],
       [61.58613592],
       [61.77565505],
       [61.60982581],
       [61.69037144],
       [61.99360206],
       [61.8751526 ],
       [61.95569824]])

In [44]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

-0.04542064768229359
